Sprint05
xholy6/MovieQuiz-ios pull request #3
Opened 2022-11-09 10:27 UTC by xholy6

Разбита логика работы приложения на несколько частей и реализован класс для ведения статистики

2022-11-09 17:27 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +    mutating func shuffleQuesions()
а зачем mutating понадобился?

2022-11-09 17:29 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        delegate?.didReceiveNextQuestion(question: questionShuffled![safe: 0])
Опционал как раз стоит развернуть в guard, делать force unwrap самое худшее что можно придумать, так как если shuffleQuesions не будет вызвана до requestNextQuestion – будет краш

2022-11-09 17:29 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +    mutating func shuffleQuesions()
давайте уберем mutating, а поставим протоколу расширение : AnyObject, должно помочь

2022-11-09 17:59 UTC, ABashkirova requested changes
Данил, привет!

Приношу извинения, кажется,  в предыдущем спринте работу перепутали и не все ошибки были поправлены вместе с ревьювером. Давайте их учтем сейчас:

1. Шрифты не отображаются. Причина в том, что ссылка на файл где-то в Downloads на вашем компьютере. Давайте удалим файлы из проекта и добавим их еще раз как было показано в уроке 
<img width="1512" alt="Screenshot 2022-11-09 at 21 45 24" src="https://user-images.githubusercontent.com/20269264/200902868-55f12b37-15e2-4ab7-969c-d010552a8e0f.png">

2. При получении цвета red приложение падает, потому что в ассетах файл назван иначе. Давайте все инициализаторы цвета исправим на те имена, которые написаны в ассетах.  Рекомендую именно так сделать, а не менять название файла с цветом, чтобы не морочиться с регистром файлов в гите.
<img width="1696" alt="Screenshot 2022-11-09 at 21 47 11" src="https://user-images.githubusercontent.com/20269264/200903108-3ad8f81f-3655-4f47-aaf9-7de7df6ff6bd.png">

3. Верстка, цвета, отступы – очень много ошибок, не все констрейнты на месте, плюс ошибки в сториборде. Давайте удалим все констрейнты и заверстаем экран с нуля. 
<img width="600" alt="Screenshot 2022-11-09 at 21 56 28" src="https://user-images.githubusercontent.com/20269264/200904810-b8c6e5e1-5608-44d6-aa7d-4a18fa52671c.png"><img width="400" alt="Screenshot 2022-11-09 at 21 55 08" src="https://user-images.githubusercontent.com/20269264/200904538-2e33e8be-3729-4fd4-b815-2af5e54924c5.png">

Из того что нужно поправить в этом спринте:

- исправить ретейн цикл и форс анврапы. 

Перед сдачей пожалуйста, проверьте работу по чеклисту: приложение должно работать и выглядеть корректно, задание этого спринта должно работать верно.

2022-11-09 17:59 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let alertText = "Ваш результат: \(correctAnswers)/\(questionsAmount) \n Количество сыгранных квизов: \(statisticService.gamesCount) \n Рекорд: \(statisticService.bestGame.toString()) \n С
будет здорово, если воспользуетесь конкатенацией или многострочной строкой, чтобы код умещался в столбец шириной 120-180 символов

2022-11-09 17:59 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    var viewController: UIViewController?
Здесь захватывается сильная ссылка на вью контроллер, получается retain cycle

2022-11-09 21:24 UTC, xholy6 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +    mutating func shuffleQuesions()
не понял как реализовать это  через AnyObject, mutating использовал для работы с questionShuffled

2022-11-09 21:29 UTC, xholy6 commented on MovieQuiz/Services/QuestionFactory.swift
> +        delegate?.didReceiveNextQuestion(question: questionShuffled![safe: 0])
Исправил, так же поправил и констрейнты, но почему то все равно багается, если я удаляю рандомный размер, например ширину кнопки в 164 - конфликт очевидно пропадает, после ,я добавляю этот же констрейнт - конфликта больше нет, но почему то скачивая архив проекта конфликт все равно есть..

2022-11-10 06:19 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +    mutating func shuffleQuesions()
Все верно. Вы объявляете протокол и описываете там функции. Протокол накладывает некоторые ограничение на эти функции. 

Когда вы их реализуете в классе или структуре: вы должны быть внимательны, функции не должны мутировать состояние объекта. Потому что протокол не знает какой тип будет реализовать протокол: ссылочный(reference type) или тип значение(value type). 

Добавляя протоколу `: AnyObject`, вы разрешаете типам подписанным на протокол иметь реализацию функций, которые могут мутировать состояние, а также быть сохраненными по слабой ссылке. Точнее не совсем так, AnyObject - говорит о том, что протоколом будет подписан ссылочный тип :)

2022-11-12 08:36 UTC, ABashkirova commented
1) Верстка выполнена верно, но лейбл не вмещается. Тут надо отступить от макета, добавить больше пространства вопросу.
2) кнопки зеленые а не белые

<img width="505" alt="Снимок экрана 2022-11-12 в 12 34 35" src="https://user-images.githubusercontent.com/20269264/201466108-ec5da196-fd19-4245-9cb7-3195d074b3fd.png">

Ошибок в сториборде нет, но есть ворнинг, - можно на него нажать и применить Update frames. После этого обновляйте значения констрейнтов.


<img width="872" alt="Снимок экрана 2022-11-12 в 12 36 40" src="https://user-images.githubusercontent.com/20269264/201466170-55aeab81-09b5-4ae5-aaa1-15771516de1c.png">

2022-11-12 08:37 UTC, ABashkirova approved these changes

2022-11-12 08:37 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            "\n Средняя точность:  \(String(format: "%.2f", statisticService.totalAccuracy))%"
Еще можно использовать вот такой синтаксис:
```
            let alertText = """
            Ваш результат: \(correctAnswers)/\(questionsAmount)
            Количество сыгранных квизов: \(statisticService.gamesCount)
            Рекорд: \(statisticService.bestGame.toString())
            Средняя точность: \(String(format: "%.2f", statisticService.totalAccuracy))%
            """
```

2022-11-12 08:37 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        guard let _ = questionShuffled else {
Если написать так:
```suggestion
        guard let questionShuffled = questionShuffled else {
```

то ниже можно использовать так:
delegate?.didReceiveNextQuestion(question: questionShuffled[safe: 0])

иначе guard использован как-то очень странно :)

2022-11-23 12:20 UTC, merged