Sprint 06
xholy6/MovieQuiz-ios pull request #8
Opened 2022-12-03 08:30 UTC by xholy6

2022-12-03 10:11 UTC, tsaidov7 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var viewController: UIViewController?
Не очень хорошо иметь ссылку на контроллер. То есть в презенторе я могу пользоваться всеми его свойствами и методами, но зачем мне это? Рекомендую его закрыть протоколом, как это сделано у вас в контроллере с фабриками и сервисами.

2022-12-03 10:12 UTC, tsaidov7 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
Почему на лоадер слабая ссылка, а само св-во публичное, тогда как на 5 первых UI-компонентов ссылка сильная, и они все приватные??

2022-12-03 10:13 UTC, tsaidov7 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showAnswerResult(isCorrect: false == currentQuestion.correctAnswer)
Зачем булево св-во сравнивать с true/false? Можно же записать 
`showAnswerResult(isCorrect: !currentQuestion.correctAnswer)`

2022-12-03 10:15 UTC, tsaidov7 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showAnswerResult(isCorrect: true == currentQuestion.correctAnswer )
showAnswerResult(isCorrect: currentQuestion.correctAnswer)

2022-12-03 10:17 UTC, tsaidov7 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            guard let self = self else { return }
Если далее у вас идет 1 строчка кода с использованием self, не стоит его разворачивать. 
```
DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [weak self] in
       self?.showNextQuestionOrResults()
}
```

2022-12-03 10:19 UTC, tsaidov7 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Объедините 2 метода showLoadingIndicator и hideLoadingIndicator в один.
```
private func drawLoader(isShown: Bool) {
       activityIndicator.isHidden = !isShown
       isShown ? activityIndicator.startAnimating() : activityIndicator.stopAnimating()
}
```

2022-12-03 10:22 UTC, tsaidov7 commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didLoadDataFromServer()
Вы не обрабатываете ошибку от сервера. Дело в том, что даже при 200 респонсе, апишка может отдать ошибку. Смотрите
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/37248555/205436237-0289ce42-1aac-49e8-96a8-6405daf6e6ba.png">

2022-12-03 10:23 UTC, tsaidov7 commented on MovieQuiz/Services/QuestionFactory.swift
> +                    self.delegate?.didLoadDataFromServer()
То есть вам необходимо сначала проверять на пустоту ключ errorMessage. Если оно не пустое, то показывать ошибку, вызывая метод делегата didFailToLoadData.

2022-12-03 10:24 UTC, tsaidov7 commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var delegate: QuestionFactoryDelegate?
Делегат инджектится через конструктор класса, значит, можно сделать его приватным.

2022-12-03 10:26 UTC, tsaidov7 commented on MovieQuiz/Services/QuestionFactory.swift
> +            DispatchQueue.main.async { [weak self] in
Ни к чему слабо захватывать self. Вы его уже слабо захватили выше, на 33 строчке.

2022-12-07 11:16 UTC, ABashkirova requested changes
В целом, работа выполнена полностью. Однако из-за нарушения зон ответственности кода, предлагаю сделать последнюю итерацию: где ты вынесешь блок кода из NetworkClient в MovieLoader.

Все остальные комментарии – опциональны. 

Также, еще раз замечу – что кнопки почему-то все еще зеленые :) 
И будет здорово, если поправишь небольшую ошибку с блокировкой кнопок. Попробуй прокликать кнопки в конце квиза, когда алерт еще не показался.

2022-12-07 11:16 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var vcDelegate: AlertPresenterDelegate?
👍🏻

2022-12-07 11:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +           activityIndicator.isHidden = !isShown
Рекомендую, использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у activityIndicator вместо ручного управления isHidden. Эту настройку можно сделать один раз во viewDidLoad или на сториборде.

2022-12-07 11:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = true
drawLoader вероятно уместнее было бы вызвать

2022-12-07 11:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.

2022-12-07 11:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +}
здесь что-то случилось с форматриованием, давай поправим` control+i`

2022-12-07 11:16 UTC, ABashkirova commented on MovieQuiz/Services/NetworkClient.swift
> +                }
оу, эта логика должна быть на уровень выше в MoviesLoader. Здесь нарушаются зоны ответственности.  Если бы в приложении был другой запрос данных, то этот сервис бы использовать стало нельзя :(

2022-12-08 20:29 UTC, ABashkirova commented on MovieQuiz/Services/NetworkClient.swift
> +                         handler(.success(data))
оступы выправить надо

2022-12-12 21:29 UTC, merged